#!/usr/bin/env python3
"""
============================================================================================
 NAKODA MIS — bundle builder
============================================================================================

 READ THIS BEFORE YOU EDIT ANY .js FILE.

 index.html no longer loads the individual modules. It loads ONE generated file,
 nakoda.bundle.js, which is every module joined together in the order they used to load in.

 So editing tasks.js and uploading it changes NOTHING on the live site. You must rebuild the
 bundle afterwards. That is what this script does.

 WHY IT IS LIKE THIS. Publishing an update used to mean dragging up to thirty files onto
 GitHub and counting them on screen, and the file that got forgotten was the file nobody saw
 (the project's own read-me used to warn "hrmodules.js keeps getting left behind"). One file
 cannot be half-uploaded.

--------------------------------------------------------------------------------------------
 HOW TO USE

   1. Edit whichever module you need — tasks.js, accounts.js, patients.js, etc.
   2. From this folder, run:

          python build-bundle.py

   3. It rewrites nakoda.bundle.js and bumps the service-worker cache version in sw.js
      (that bump is what makes browsers fetch the new build instead of the cached one).
   4. Copy index.html, nakoda.bundle.js and sw.js into GITHUB-FOLDER, then upload
      GITHUB-FOLDER to GitHub.

   Run with --check to verify without writing anything:

          python build-bundle.py --check

--------------------------------------------------------------------------------------------
 RULES

   * ORDER MATTERS and is fixed in MODULES below. api.js must come before app.js; patients.js
     must come after ops.js and membership.js because it calls into their modals. If you add a
     new module, put it in the right place in that list — not at the end by default.
   * config.js is NEVER bundled. It holds this installation's live /exec URL and must not be
     overwritten by an update.
   * Do not edit nakoda.bundle.js by hand. It is generated, and your change will be lost the
     next time anyone runs this.
============================================================================================
"""

import sys, os, re, datetime

# The load order. This is the order index.html used before bundling — do not shuffle it.
MODULES = [
    'api.js',            # data layer + offline outbox — must be first
    'punchq.js',         # offline attendance punch queue
    'app.js',            # shell, routing, dashboard — defines $, esc, toast, openModal…
    'branches.js',
    'watemplates.js',
    'membership.js',     # must precede patients.js (openIssueCardModal)
    'bulksend.js',
    'messaging.js',     # Bulk Message Send (Timely Message will join later)
    'cardadmin.js',
    'tasks.js',
    'calendar.js',
    'attendance.js',
    'hrmodules.js',
    'leave.js',
    'accounts.js',
    'training.js',
    'assets.js',
    'inventory.js',
    'stockauto.js',
    'purchase.js',
    'payreq.js',
    'combo.js',
    'recurring.js',
    'finance.js',
    'statementtable.js',
    'bankpreview.js',
    'ops.js',            # must precede patients.js (openCollectSample)
    'patients.js',       # Patient CRM
    'quicklog.js',
    'extras.js',
]

OUT = 'nakoda.bundle.js'
SW  = 'sw.js'


def fail(msg):
    print('\n  ERROR: ' + msg + '\n')
    sys.exit(1)


def main():
    check_only = '--check' in sys.argv
    here = os.path.dirname(os.path.abspath(__file__))
    os.chdir(here)

    missing = [m for m in MODULES if not os.path.exists(m)]
    if missing:
        fail('these modules are listed in MODULES but not in this folder:\n         ' +
             ', '.join(missing))

    stray = [f for f in sorted(os.listdir('.'))
             if f.endswith('.js') and f not in MODULES
             and f not in (OUT, SW, 'config.js')]
    if stray:
        print('  NOTE: these .js files are in the folder but NOT in the bundle:')
        for f in stray:
            print('        ' + f + '   (add it to MODULES if it should ship)')
        print()

    # ---- build ----
    header = (
        '/* ============================================================================================\n'
        ' *  NAKODA MIS - bundled application script\n'
        ' *\n'
        ' *  %d source files, joined in exactly the order index.html used to load them.\n'
        ' *  Generated by build-bundle.py on %s. DO NOT EDIT THIS FILE - edit the\n'
        ' *  individual modules and run the script again, or your change will be overwritten.\n'
        ' *\n'
        ' *  config.js is deliberately NOT included: it holds the live /exec URL.\n'
        ' * ============================================================================================ */\n'
        % (len(MODULES), datetime.date.today().isoformat())
    )

    parts = [header]
    for m in MODULES:
        with open(m, encoding='utf-8') as fh:
            src = fh.read()
        parts.append('\n\n/* ==== %s %s */\n' % (m, '=' * max(0, 68 - len(m))))
        parts.append(src)
        if not src.endswith('\n'):
            parts.append('\n')
    bundle = ''.join(parts)

    # ---- bump the cache version so browsers actually fetch the new build ----
    new_ver = None
    if os.path.exists(SW):
        with open(SW, encoding='utf-8') as fh:
            sw = fh.read()
        m = re.search(r"nakoda-mis-v(\d+)", sw)
        if m:
            new_ver = int(m.group(1)) + 1
            sw_new = re.sub(r"nakoda-mis-v\d+", 'nakoda-mis-v%d' % new_ver, sw, count=1)
        else:
            print('  WARNING: no cache version found in sw.js — browsers may keep the old build.')
            sw_new = sw
    else:
        print('  WARNING: sw.js not found — cache version not bumped.')
        sw_new = None

    if check_only:
        print('  CHECK ONLY — nothing written.')
        print('  would bundle : %d modules, %s KB, %s lines'
              % (len(MODULES), round(len(bundle.encode()) / 1024), format(bundle.count('\n'), ',')))
        if new_ver:
            print('  would bump   : cache version -> nakoda-mis-v%d' % new_ver)
        return

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(bundle)
    if sw_new is not None:
        with open(SW, 'w', encoding='utf-8') as fh:
            fh.write(sw_new)

    print('  built %s   %s KB, %s lines, %d modules'
          % (OUT, round(len(bundle.encode()) / 1024), format(bundle.count('\n'), ','), len(MODULES)))
    if new_ver:
        print('  cache version -> nakoda-mis-v%d' % new_ver)
    print()
    print('  NEXT: copy index.html, nakoda.bundle.js and sw.js into GITHUB-FOLDER,')
    print('        then upload GITHUB-FOLDER to GitHub and hard-refresh (Ctrl+Shift+R).')


if __name__ == '__main__':
    main()
